# Generated by Django 4.1.4 on 2022-12-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cms_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_heading', models.CharField(max_length=30)),
                ('page_meta_title', models.CharField(max_length=30)),
                ('page_content', models.CharField(max_length=30)),
                ('page_meta_description', models.CharField(max_length=30)),
                ('page_canonical_url', models.CharField(max_length=30)),
            ],
        ),
    ]
