# Generated by Django 4.1.4 on 2022-12-15 18:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms_page',
            name='page_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
