# Generated by Django 4.1.4 on 2022-12-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_cms_page_page_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms_page',
            name='page_meta_description',
            field=models.TextField(max_length=300),
        ),
    ]
