# Generated by Django 4.1.4 on 2022-12-15 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_rename_cms_page_pages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pages',
            new_name='Page',
        ),
    ]
