# Generated by Django 4.1.4 on 2022-12-19 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_members'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Members',
        ),
    ]
