# Generated by Django 4.1.4 on 2022-12-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author_name', models.CharField(max_length=30)),
                ('Author_bio', models.CharField(max_length=30)),
                ('Author_pic', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_title', models.CharField(max_length=30)),
                ('Post_description', models.CharField(max_length=30)),
            ],
        ),
    ]
