# Generated by Django 4.1.4 on 2022-12-19 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Author_bio',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Post_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Post_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='author',
            name='Author_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='Author_pic',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='blog.author'),
        ),
    ]
