# Generated by Django 4.1.4 on 2022-12-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(default='hello', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title',
            field=models.CharField(default='hello', max_length=30),
        ),
    ]
