# Generated by Django 4.1.4 on 2022-12-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_meta_description_post_meta_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.TextField(default='', max_length=100),
        ),
    ]
