# Generated by Django 4.1.4 on 2022-12-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_meta_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='meta_title',
            field=models.CharField(default='', max_length=30),
        ),
    ]
